### ISSUE TITLE
Renaming note crashes then breaks backend

### ISSUE THREAD

**Issue by ebdmuir** [unigraph-dev/unigraph-dev#230]
I tried renaming a note in the notes interface which kept reseting to its original then I went into the JSON viewer to edit it, which resulted in a crash with this error:

```js
Building entity part error: Error: Building entity part error: TypeError: Schema check failure for object: "Thoughts about Unigraph"{"uid":"0x50dc","_properties":[{"uid":"0x50dd","_definition":{"uid":"0x50d6","type":{"uid":"0x4e8d","unigraph.id":"$/schema/interface/textual","dgraph.type":["Type"]}},"_indexAs":"name","_key":"text"},{"uid":"0x50de","_definition":{"uid":"0x50d4","_parameters":{"uid":"0x50da","_element":{"uid":"0x50d7","_parameters":{"uid":"0x50d3","_definitions":[{"uid":"0x50d8","type":{"uid":"0x4e4f","unigraph.id":"$/schema/subentity","dgraph.type":["Type"]}},{"uid":"0x50d9","type":{"uid":"0x4e4b","unigraph.id":"$/schema/interface/semantic","dgraph.type":["Type"]}}]},"type":{"uid":"0x4e2b","unigraph.id":"$/composer/Union"}}},"type":{"uid":"0x4e2a","unigraph.id":"$/composer/Array"}},"_key":"children"}],"_parameters":{"uid":"0x50d5","_indexedBy":{"uid":"0x4e26","unigraph.id":"$/primitive/string"}},"type":{"uid":"0x4e2c","unigraph.id":"$/composer/Object"}}$/primitive/string"Thoughts about Unigraph"{"uid":"0x50dc","_properties":[{"uid":"0x50dd","_definition":{"uid":"0x50d6","type":{"uid":"0x4e8d","unigraph.id":"$/schema/interface/textual","dgraph.type":["Type"]}},"_indexAs":"name","_key":"text"},{"uid":"0x50de","_definition":{"uid":"0x50d4","_parameters":{"uid":"0x50da","_element":{"uid":"0x50d7","_parameters":{"uid":"0x50d3","_definitions":[{"uid":"0x50d8","type":{"uid":"0x4e4f","unigraph.id":"$/schema/subentity","dgraph.type":["Type"]}},{"uid":"0x50d9","type":{"uid":"0x4e4b","unigraph.id":"$/schema/interface/semantic","dgraph.type":["Type"]}}]},"type":{"uid":"0x4e2b","unigraph.id":"$/composer/Union"}}},"type":{"uid":"0x4e2a","unigraph.id":"$/composer/Array"}},"_key":"children"}],"_parameters":{"uid":"0x50d5","_indexedBy":{"uid":"0x4e26","unigraph.id":"$/primitive/string"}},"type":{"uid":"0x4e2c","unigraph.id":"$/composer/Object"}}$/primitive/string
"Thoughts about Unigraph"{"uid":"0x50e6","type":{"uid":"0x50df","unigraph.id":"$/schema/note_block","dgraph.type":["Type"]}}$/primitive/string

/Users/ericmuir/Projects/unigraph/packages/unigraph-dev-common/lib/utils/entityUtils.js:249
            throw new Error('Building entity part error: ' + e + JSON.stringify(rawPart) + JSON.stringify(localSchema) + rawPartUnigraphType + '\n');
                  ^

Error: Building entity part error: Error: Building entity part error: Error: Building entity part error: TypeError: Union type does not allow ambiguous or nonexistent selections!"Thoughts about Unigraph"{"uid":"0x50e5","type":{"uid":"0x4e2b","unigraph.id":"$/composer/Union"},"_parameters":{"uid":"0x50e7","_definitions":[{"uid":"0x4e87","type":{"uid":"0x4e80","unigraph.id":"$/schema/note","dgraph.type":["Type"]}},{"uid":"0x4e89","type":{"uid":"0x4e83","unigraph.id":"$/schema/html","dgraph.type":["Type"]}},{"uid":"0x4e8a","type":{"uid":"0x4e86","unigraph.id":"$/schema/markdown","dgraph.type":["Type"]}},{"uid":"0x50e6","type":{"uid":"0x50df","unigraph.id":"$/schema/note_block","dgraph.type":["Type"]}}]}}$/primitive/string
available types: $/schema/note ,$/schema/html ,$/schema/markdown ,$/schema/note_block 

"Thoughts about Unigraph"{"uid":"0x50e5","type":{"uid":"0x4e2b","unigraph.id":"$/composer/Union"},"_parameters":{"uid":"0x50e7","_definitions":[{"uid":"0x4e87","type":{"uid":"0x4e80","unigraph.id":"$/schema/note","dgraph.type":["Type"]}},{"uid":"0x4e89","type":{"uid":"0x4e83","unigraph.id":"$/schema/html","dgraph.type":["Type"]}},{"uid":"0x4e8a","type":{"uid":"0x4e86","unigraph.id":"$/schema/markdown","dgraph.type":["Type"]}},{"uid":"0x50e6","type":{"uid":"0x50df","unigraph.id":"$/schema/note_block","dgraph.type":["Type"]}}]}}$/primitive/string
"Thoughts about Unigraph"{"uid":"0x50d6","type":{"uid":"0x4e8d","unigraph.id":"$/schema/interface/textual","dgraph.type":["Type"]}}$/primitive/string
{"text":"Thoughts about Unigraph"}{"uid":"0x50dc","_properties":[{"uid":"0x50dd","_definition":{"uid":"0x50d6","type":{"uid":"0x4e8d","unigraph.id":"$/schema/interface/textual","dgraph.type":["Type"]}},"_indexAs":"name","_key":"text"},{"uid":"0x50de","_definition":{"uid":"0x50d4","_parameters":{"uid":"0x50da","_element":{"uid":"0x50d7","_parameters":{"uid":"0x50d3","_definitions":[{"uid":"0x50d8","type":{"uid":"0x4e4f","unigraph.id":"$/schema/subentity","dgraph.type":["Type"]}},{"uid":"0x50d9","type":{"uid":"0x4e4b","unigraph.id":"$/schema/interface/semantic","dgraph.type":["Type"]}}]},"type":{"uid":"0x4e2b","unigraph.id":"$/composer/Union"}}},"type":{"uid":"0x4e2a","unigraph.id":"$/composer/Array"}},"_key":"children"}],"_parameters":{"uid":"0x50d5","_indexedBy":{"uid":"0x4e26","unigraph.id":"$/primitive/string"}},"type":{"uid":"0x4e2c","unigraph.id":"$/composer/Object"}}$/composer/Object

    at buildUnigraphEntityPart (/Users/ericmuir/Projects/unigraph/packages/unigraph-dev-common/lib/utils/entityUtils.js:249:19)
    at Object.buildUnigraphEntity (/Users/ericmuir/Projects/unigraph/packages/unigraph-dev-common/lib/utils/entityUtils.js:309:36)
    at Object.update_object (/Users/ericmuir/Projects/unigraph/packages/unigraph-dev-backend/dist/server.js:284:57)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

Now when I restart the server I get the following error:

```js
/Users/ericmuir/Projects/unigraph/packages/unigraph-dev-common/lib/utils/entityUtils.js:423
    var localSchema = schemaMap[schemaName]._definition;
                                            ^

TypeError: Cannot read property '_definition' of undefined
    at Object.makeQueryFragmentFromType (/Users/ericmuir/Projects/unigraph/packages/unigraph-dev-common/lib/utils/entityUtils.js:423:45)
    at Object.subscribeToType (/Users/ericmuir/Projects/unigraph/packages/unigraph-dev-backend/dist/localUnigraphApi.js:47:119)
    at /Users/ericmuir/Projects/unigraph/packages/unigraph-dev-backend/dist/server.js:135:39
    at exec (/Users/ericmuir/Projects/unigraph/node_modules/async-lock/lib/index.js:127:4)
    at AsyncLock.acquire (/Users/ericmuir/Projects/unigraph/node_modules/async-lock/lib/index.js:152:3)
    at Object.subscribe_to_type (/Users/ericmuir/Projects/unigraph/packages/unigraph-dev-backend/dist/server.js:133:18)
    at WebSocket.<anonymous> (/Users/ericmuir/Projects/unigraph/packages/unigraph-dev-backend/dist/server.js:423:49)
    at WebSocket.emit (node:events:369:20)
    at WebSocket.emit (node:domain:470:12)
    at Receiver.receiverOnMessage (/Users/ericmuir/Projects/unigraph/node_modules/ws/lib/websocket.js:835:20)
```

I'm going to try dig into the issue myself but as it's a totally new codebase to me it'll take me some time to get my head around. As per usual I'll get a PR in if I can fix the issue but any help would be grand.

Cheers,
Eric
(101stArrow on your Discord)

**Comment by thesophiaxu** [comment]
The bug when you restart is because the server accepts connections before it loads the database - for now just close all frontend windows before restarting it and I'll push an update soon.

The JSON viewer is kinda broken, I'll take a look at it, but in the meantime you can use the rich object viewer or just click on the note title to rename :)

**Comment by ebdmuir** [comment]
When I modify the title in the notes viewer itself, it reverts to its original title when I click out the box - I'll grab a recording if you want. Finally worked out how to edit the object in the rich viewer, hadn't thought to flick the switch.

**Comment by thesophiaxu** [comment]
Yeah, a recording would be great! I'll see if I can replicate it in a new database too - couldn't replicate in the current one

**Comment by thesophiaxu** [comment]
Trying to fix it now!

**Comment by thesophiaxu** [comment]
Hi! My recent push should fixed the issue when renaming it directly from the window, so I'm closing this for now - lemme know by reopening this issue if the bug reappeared for you!
