### ISSUE TITLE
`yarn backend-start` fails after commit 23b47923

### ISSUE THREAD

**Issue by asampal** [unigraph-dev/unigraph-dev#275]
Getting the following error after pulling latest and doing `yarn, yarn build-deps, yarn backend-start`.

```
❯ yarn backend-start
yarn run v1.22.17
$ yarn workspace unigraph-dev-backend start
warning package.json: No license field
$ yarn build && node --trace-warnings dist
warning package.json: No license field
$ run-script-os
warning package.json: No license field
$ pwsh -Command "tsc && (Copy-Item ../../secrets.env.json.gpg -Destination dist)"
Actually doing the upsert...
Error: 2 UNKNOWN: : Query couldn't be executed
    at Object.callErrorFromStatus (D:\dev\projects-open-source\unigraph-dev\node_modules\@grpc\grpc-js\build\src\call.js:31:26)
    at Object.onReceiveStatus (D:\dev\projects-open-source\unigraph-dev\node_modules\@grpc\grpc-js\build\src\client.js:176:52)
    at Object.onReceiveStatus (D:\dev\projects-open-source\unigraph-dev\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:336:141)
    at Object.onReceiveStatus (D:\dev\projects-open-source\unigraph-dev\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:299:181)
    at D:\dev\projects-open-source\unigraph-dev\node_modules\@grpc\grpc-js\build\src\call-stream.js:145:78
    at processTicksAndRejections (node:internal/process/task_queues:76:11) {
  code: 2,
  details: ": Query couldn't be executed",
  metadata: Metadata {
    internalRepr: Map(1) { 'content-type' => [Array] },
    options: {}
  }
}
D:\dev\projects-open-source\unigraph-dev\packages\unigraph-dev-backend\dist\dgraphClient.js:257
        const tns = res.getLatency().getTotalNs();
                        ^

TypeError: res.getLatency is not a function
    at DgraphClient.queryDgraph (D:\dev\projects-open-source\unigraph-dev\packages\unigraph-dev-backend\dist\dgraphClient.js:257:25)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async DgraphClient.getSchemasFromTable (D:\dev\projects-open-source\unigraph-dev\packages\unigraph-dev-backend\dist\dgraphClient.js:303:22)
    at async Object.cache.updateNow (D:\dev\projects-open-source\unigraph-dev\packages\unigraph-dev-backend\dist\datamodelManager.js:43:25)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: C:\Program Files\nodejs\node.exe
Arguments: d:\dev\nvm\v15.14.0\node_modules\yarn\lib\cli.js start
Directory: D:\dev\projects-open-source\unigraph-dev\packages\unigraph-dev-backend
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
adi@VESUVIUS  D:\dev\projects-open-source\unigraph-dev   main ↑5                                                                                       [22:02]
```

**Comment by thesophiaxu** [comment]
Was able to reproduce & fix - should work now!
