### ISSUE TITLE
Local backend crash when adding bookmark

### ISSUE THREAD

**Issue by asampal** [unigraph-dev/unigraph-dev#289]
To reproduce:

- `Ctrl + e` to bring up omnibar
- enter `+bm https://dgraph.io/docs/get-started/` and hit `Enter` to add the bookmark
- observe the following output in the console where `yarn backend-start` was run:

```
D:\dev\projects-open-source\unigraph-dev\packages\unigraph-dev-backend\dist\localUnigraphApi.js:338
                const exec = uid.startsWith("0x") ? entityUtils_1.unpad((await client.queryUID(uid))[0]) : states.caches["executables"].data[uid];
                                 ^

TypeError: Cannot read property 'startsWith' of undefined
    at D:\dev\projects-open-source\unigraph-dev\packages\unigraph-dev-backend\dist\localUnigraphApi.js:338:34
    at exec (D:\dev\projects-open-source\unigraph-dev\node_modules\async-lock\lib\index.js:127:4)
    at AsyncLock.acquire (D:\dev\projects-open-source\unigraph-dev\node_modules\async-lock\lib\index.js:152:3)
    at Object.runExecutable (D:\dev\projects-open-source\unigraph-dev\packages\unigraph-dev-backend\dist\localUnigraphApi.js:337:31)
    at Object.eval (eval at runEnvRoutineJs (D:\dev\projects-open-source\unigraph-dev\packages\unigraph-dev-backend\dist\executableManager.js:96:16), <anonymous>:28:48)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async D:\dev\projects-open-source\unigraph-dev\packages\unigraph-dev-backend\dist\executableManager.js:61:29
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: C:\Program Files\nodejs\node.exe
Arguments: d:\dev\nvm\v15.14.0\node_modules\yarn\lib\cli.js start
Directory: D:\dev\projects-open-source\unigraph-dev\packages\unigraph-dev-backend
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Windows 11, Unigraph 16d448f

**Comment by thesophiaxu** [comment]
Fixed!

**Comment by asampal** [comment]
Unfortunately I'm still getting the crash, @thesophiaxu

**Comment by thesophiaxu** [comment]
the fix is in one of the packages, so you'll need to overwrite the package `unigraph.bookmarks` with `packages/unigraph-dev-common/lib/data/unigraph.bookmarks.pkg.js` in the package manager

**Comment by asampal** [comment]
Thanks, that did it. For a dev environment do you intend to, at some point, update the package automatically if it's been updated outside of Dgraph? I guess a simple file watcher wouldn't be enough since you'd need to compare FS package version with DB version.
