### ISSUE TITLE
Schema error on `yarn backend-start`

### ISSUE THREAD

**Issue by asampal** [unigraph-dev/unigraph-dev#304]
After pulling latest I get the following error on doing `yarn backend-start`:

```
❯ yarn backend-start       
yarn run v1.22.17
$ yarn workspace unigraph-dev-backend start
warning package.json: No license field
$ yarn build && node --trace-warnings dist
warning package.json: No license field
$ run-script-os
warning package.json: No license field
$ pwsh -Command "tsc && (Copy-Item ../../secrets.env.json.gpg -Destination dist)"
D:\dev\projects-open-source\unigraph-dev\node_modules\@grpc\grpc-js\build\src\call.js:31
    return Object.assign(new Error(message), status);
                         ^

Error: 2 UNKNOWN: Schema does not contain a matching predicate for field definition in type Type
    at Object.callErrorFromStatus (D:\dev\projects-open-source\unigraph-dev\node_modules\@grpc\grpc-js\build\src\call.js:31:26)
    at Object.onReceiveStatus (D:\dev\projects-open-source\unigraph-dev\node_modules\@grpc\grpc-js\build\src\client.js:176:52)
    at Object.onReceiveStatus (D:\dev\projects-open-source\unigraph-dev\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:336:141)
    at Object.onReceiveStatus (D:\dev\projects-open-source\unigraph-dev\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:299:181)
    at D:\dev\projects-open-source\unigraph-dev\node_modules\@grpc\grpc-js\build\src\call-stream.js:145:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 2,
  details: 'Schema does not contain a matching predicate for field definition in type Type',
  metadata: Metadata {
    internalRepr: Map(1) { 'content-type' => [ 'application/grpc' ] },
    options: {}
  }
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: C:\Program Files\nodejs\node.exe
Arguments: d:\dev\nvm\v16.13.1\node_modules\yarn\lib\cli.js start
Directory: D:\dev\projects-open-source\unigraph-dev\packages\unigraph-dev-backend
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Windows 11, Unigraph a82ac197

**Comment by thesophiaxu** [comment]
Thanks! Probably the new code formatter broke some of them. I'll take a look at it.

**Comment by thesophiaxu** [comment]
turns out that the formatter ate my underscore in a string but only in one place. It should be fixed now
