### ISSUE TITLE
Fails to build in Docker

### ISSUE THREAD

**Issue by yonas** [unigraph-dev/unigraph-dev#461]
```
warning " > @babel/eslint-parser@7.13.14" has unmet peer dependency "@babel/core@>=7.11.0".
warning " > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-syntax-flow@^7.14.5".
warning " > eslint-plugin-flowtype@8.0.3" has unmet peer dependency "@babel/plugin-transform-react-jsx@^7.14.9".
warning "workspace-aggregator-bbae34d0-3434-4676-9bdc-8442d98e1ea5 > unigraph-dev-explorer > @monaco-editor/react@4.1.3" has incorrect peer dependency "monaco-editor@^0.23.0".
warning "workspace-aggregator-bbae34d0-3434-4676-9bdc-8442d98e1ea5 > unigraph-dev-explorer > @sandstreamdev/react-swipeable-list@1.0.1" has unmet peer dependency "prop-types@^15.7.2".
warning "workspace-aggregator-bbae34d0-3434-4676-9bdc-8442d98e1ea5 > unigraph-dev-explorer > eslint-webpack-plugin@2.5.3" has incorrect peer dependency "eslint@^7.0.0".
warning "workspace-aggregator-bbae34d0-3434-4676-9bdc-8442d98e1ea5 > unigraph-dev-explorer > react-splitter-layout@4.0.0" has unmet peer dependency "prop-types@^15.5.0".
warning "workspace-aggregator-bbae34d0-3434-4676-9bdc-8442d98e1ea5 > unigraph-dev-explorer > react-splitter-layout@4.0.0" has incorrect peer dependency "react@^15.5.0 || ^16.0.0".
warning "workspace-aggregator-bbae34d0-3434-4676-9bdc-8442d98e1ea5 > unigraph-dev-explorer > @testing-library/user-event@7.2.1" has unmet peer dependency "@testing-library/dom@>=5".
[5/5] Building fresh packages...
error /app/node_modules/nlapack, /app/packages/unigraph-dev-electron/node_modules/nlapack: Command failed.
Exit code: 1
Command: npm run build
Arguments: 
Directory: /app/packages/unigraph-dev-electron/node_modules/nlapack
Output:
> nlapack@2.0.4 build
> node-gyp rebuild -j max

gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@16.17.0 | linux | x64
gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
gyp http GET https://nodejs.org/download/release/v16.17.0/node-v16.17.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v16.17.0/node-v16.17.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v16.17.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v16.17.0/SHASUMS256.txt
(node:116) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/app/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/app/packages/unigraph-dev-electron/node_modules/nlapack/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/app/node_modules/@npmcli/run-script/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.cache/node-gyp/16.17.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/16.17.0',
gyp info spawn args   '-Dnode_gyp_dir=/app/node_modules/@npmcli/run-script/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/16.17.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/app/packages/unigraph-dev-electron/node_modules/nlapack',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/app/node_modules/@npmcli/run-script/node_modules/which/which.js:10:17)
gyp ERR! stack     at /app/node_modules/@npmcli/run-script/node_modules/which/which.js:57:18
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at step (/app/node_modules/@npmcli/run-script/node_modules/which/which.js:54:21)
gyp ERR! stack     at /app/node_modules/@npmcli/run-script/node_modules/which/which.js:71:22
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at subStep (/app/node_modules/@npmcli/run-script/node_modules/which/which.js:69:33)
gyp ERR! stack     at /app/node_modules/@npmcli/run-script/node_modules/which/which.js:80:22
gyp ERR! stack     at /app/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /app/node_modules/isexe/mode.js:8:5
gyp ERR! System Linux 5.15.0-48-generic
gyp ERR! command "/usr/bin/node" "/app/node_modules/.bin/node-gyp" "rebuild" "-j" "max"
gyp ERR! cwd /app/packages/unigraph-dev-electron/node_modules/nlapack
gyp ERR! node -v v16.17.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c cd /app && yarn --network-timeout 600000' returned a non-zero code: 1
```

Using checkout [1613443](https://github.com/unigraph-dev/unigraph-dev/commit/1613443fe0370e7d149afb5c179d93f41fd7d3fd).

**Comment by Terramoto** [comment]
added build-essential to the apt RUN in order to bypass this error. Also `|| true` both yarn runs

**Comment by yonas** [comment]
Thanks @Terramoto, I've created a pull request #462.

**Comment by allefgomes** [comment]
Hello, everyone.
I'm trying to build and added build-essentials as mentioned above, but it don't works for me.

I'm getting a error that not exists the lib **lapacke.h**.
![image](https://user-images.githubusercontent.com/25732016/219036979-e73cd339-e3c0-4610-aede-943c322169d2.png)

How can I solve this?

**Comment by Terramoto** [comment]
> Hello, everyone. I'm trying to build and added build-essentials as mentioned above, but it don't works for me.
> 
> I'm getting a error that not exists the lib **lapacke.h**. ![image](https://user-images.githubusercontent.com/25732016/219036979-e73cd339-e3c0-4610-aede-943c322169d2.png)
> 
> How can I solve this?

Might need to add the following command to the Dockerfile
`RUN apt install -y libblas-dev liblapack-dev liblapacke-dev`
